"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpenText, Check, FileSearch, Layers3, MessagesSquare, Quote, ShieldCheck, TrendingDown } from "lucide-react";
import InlineLeadCapture from "./InlineLeadCapture";
import { useLeadModal } from "./LeadModalContext";
import s from "./SiteHome.module.css";

const reviews=[
{name:"Restaurant owner",role:"Hospitality · sample review",image:"https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"The first conversation helped me separate what was urgent from what simply felt urgent. That made the next decision easier to think through."},
{name:"Manufacturing owner",role:"Manufacturing · sample review",image:"https://images.pexels.com/photos/3862627/pexels-photo-3862627.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"I wanted someone to understand the operating side of the business, not just look at a balance. The review finally felt organized."},
{name:"Retail operator",role:"Retail · sample review",image:"https://images.pexels.com/photos/3768131/pexels-photo-3768131.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"The process gave me a clearer idea of what information to gather and what questions I should be asking next."},
];
const steps=[["01","Understand the situation","Start with what is changing inside the business and where cash flow is becoming difficult."],["02","Map the obligations","Organize active advances, balances, withdrawal cadence, and immediate operating priorities."],["03","Review possible paths","Compare realistic options, tradeoffs, and any information still needed before a decision."],["04","Move with a plan","If you choose to proceed, keep communication, documentation, and follow-up organized."]];

export default function SiteHome({onContinue:_onContinue}:{onContinue:(a:string,b:string)=>void}){
 const openLead=useLeadModal(); const[story,setStory]=useState(0); const active=reviews[story]; const move=(d:number)=>setStory((story+d+reviews.length)%reviews.length);
 return <>
 <section id="top" className={s.hero}><div className={`${s.wrap} ${s.heroGrid}`}><div className={s.copy}><span className={s.kicker}>RESTORE OPERATING FLEXIBILITY</span><h1>Reclaim room to run your business.</h1><p>Revive MCA helps business owners understand how merchant cash advance obligations are affecting day-to-day operations and prepare for a more informed conversation about what comes next.</p><div className={s.actions}><button onClick={openLead}>Request a private consultation <ArrowRight/></button><a href="#revive-process">See how the review works</a></div><div className={s.proof}><span><ShieldCheck/>Confidential intake</span><span><Check/>Business-purpose focus</span><span><Check/>No guaranteed outcomes</span></div></div><div className={s.formWrap}><InlineLeadCapture title="Request a private consultation" button="Request my consultation"/></div></div><div className={s.signal}><div><strong>Daily withdrawals</strong><span>See what is being drawn and when.</span></div><div><strong>Stacked advances</strong><span>Understand the combined weekly effect.</span></div><div><strong>Operating priorities</strong><span>Keep payroll, rent, inventory, and vendors visible.</span></div><div><strong>Clear next move</strong><span>Prepare for a more informed decision.</span></div></div></section>

 <section className={s.editorial}><div className={`${s.wrap} ${s.editorialGrid}`}><div><span className={s.kicker}>WHAT CHANGES INSIDE THE BUSINESS</span><h2>When withdrawals stop fitting the operating cycle.</h2><p>Merchant cash advances can become difficult when the payment cadence no longer matches the way revenue actually arrives. The issue may show up as delayed vendor payments, tighter payroll timing, reduced inventory flexibility, or repeated transfers just to keep the account balanced.</p><p>A useful review starts by understanding those operating effects, not by jumping immediately to another financing product.</p></div><div className={s.sideNote}><strong>WHAT TO PREPARE BEFORE A REVIEW</strong><p>Recent bank statements, MCA agreements, estimated balances, withdrawal schedules, and any notices or collection communications. These details can make the conversation more useful, but they are not required to submit the initial contact form.</p></div></div></section>

 <section id="solutions" className={s.situations}><div className={s.wrap}><div className={s.sectionHead}><span>COMMON BUSINESS SITUATIONS</span><h2>Look at the operating problem from four angles.</h2><p>Each situation affects a business differently, which is why the review should focus on the actual payment structure and operating reality.</p></div><div className={s.situationGrid}><article><TrendingDown/><h3>Cash-flow disruption</h3><p>Withdrawals are competing with payroll, inventory, taxes, rent, or essential vendors.</p></article><article><Layers3/><h3>Stacked advances</h3><p>Several obligations are drawing from the same revenue and need to be reviewed together.</p></article><article><MessagesSquare/><h3>Escalating contact</h3><p>Calls, notices, and follow-up are consuming time that should be spent running the company.</p></article><article><FileSearch/><h3>Agreement questions</h3><p>Owners need a clearer view of payment mechanics, balances, documents, and next questions.</p></article></div></div></section>

 <section id="revive-process" className={s.process}><div className={`${s.wrap} ${s.processGrid}`}><div className={s.processIntro}><span className={s.kicker}>A MORE DELIBERATE PROCESS</span><h2>From operating strain to an organized decision.</h2><p>The process is designed to reduce confusion, surface the right facts, and make the next conversation easier to navigate.</p></div><div className={s.journey}>{steps.map((x,i)=><article key={x[0]}><div className={s.node}>{i+1}</div><div className={s.step}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>

 <section id="stories" className={s.stories}><div className={s.wrap}><div className={s.sectionHead}><span>BUSINESS-OWNER PERSPECTIVE</span><h2>Stories should feel specific, not manufactured.</h2><p>Sample staging content only. Replace with client-approved testimonials and photography before production.</p></div><div className={s.storyMain}><img src={active.image} alt={active.name}/><div className={s.storyCopy}><Quote/><p>“{active.quote}”</p><strong>{active.name}</strong><span>{active.role}</span></div></div><div className={s.storyControls}><button onClick={()=>move(-1)} aria-label="Previous story"><ArrowLeft size={18}/></button><div className={s.dots}>{reviews.map((_,i)=><button key={i} aria-label={`Story ${i+1}`} onClick={()=>setStory(i)} className={`${s.dot} ${i===story?s.active:""}`}/>)}</div><button onClick={()=>move(1)} aria-label="Next story"><ArrowRight size={18}/></button></div></div></section>

 <section className={s.resources}><div className={`${s.wrap} ${s.resourceBox}`}><div><BookOpenText/><span className={s.kicker}>INSIGHTS & RESOURCES</span><h2>Useful answers before the consultation.</h2><p>Educational content gives visitors something valuable even if they are not ready to submit a form. The resource center covers withdrawal mechanics, stacked advances, documentation, and questions to consider before speaking with a consultant.</p></div><a href="/insights">Explore resources <ArrowRight/></a></div></section>
 </>;
}
